return {
    "Civitasv/cmake-tools.nvim",
    cmd = {
        "CMakeBuild",
        "CMakeBuild",
        "CMakeBuildCurrentFile",
        "CMakeClean",
        "CMakeCloseExecutor",
        "CMakeCloseRunner",
        "CMakeDebug",
        "CMakeDebugCurrentFile",
        "CMakeGenerate",
        "CMakeInstall",
        "CMakeLaunchArgs",
        "CMakeOpenCache",
        "CMakeOpenExecutor",
        "CMakeOpenRunner",
        "CMakeQuickBuild",
        "CMakeQuickDebug",
        "CMakeQuickRun",
        "CMakeQuickStart",
        "CMakeRun",
        "CMakeRunCurrentFile",
        "CMakeRunTest",
        "CMakeSelectBuildDir",
        "CMakeSelectBuildPreset",
        "CMakeSelectBuildTarget",
        "CMakeSelectBuildType",
        "CMakeSelectConfigurePreset",
        "CMakeSelectCwd",
        "CMakeSelectKit",
        "CMakeSelectLaunchTarget",
        "CMakeSelectTestPreset",
        "CMakeSettings",
        "CMakeShowTargetFiles",
        "CMakeStopExecutor",
        "CMakeStopRunner",
        "CMakeTargetSettings"
    },
    ft = { "cmake", "cpp", "c" },
    keys = {
        "<leader>cg",
        "<leader>cb",
    },
    dependencies = {
        "nvim-lua/plenary.nvim",
    },
    opts = {
        cmake_build_directory = "build"
    },
}
